blueprint:
  name: "Radiateur fil pilote - Régulation PWM (cycle 30s ou 5 min) + zone morte + sécurité"
  description: >
    Régulation temporelle (PWM).
    - Relais OFF = chauffe (Confort)
    - Relais ON  = hors-gel / arrêt
    - Zone morte (deadband)
    - Capteur indisponible => chauffe X% (défaut 50%)
    - Mode Hors Gel prioritaire
    - Cycle configurable: 30s (test) ou 5 min (prod)
  domain: automation

  input:
    fil_pilote_switch:
      name: "Relais / prise fil pilote"
      description: "Switch commandant le fil pilote (OFF=chauffe, ON=hors-gel)."
      selector:
        entity:
          domain: switch

    thermometre:
      name: "Capteur de température"
      selector:
        entity:
          domain: sensor

    mode_chauffage:
      name: "Mode chauffage (input_select)"
      description: "Doit contenir les valeurs 'Confort' et 'Hors Gel'."
      selector:
        entity:
          domain: input_select

    consigne:
      name: "Consigne (input_number)"
      selector:
        entity:
          domain: input_number

    cycle:
      name: "Cycle PWM"
      description: "Choisir 30s (test) ou 5 min (prod)."
      default: "5 min"
      selector:
        select:
          options:
            - "30 s"
            - "5 min"

    coeff:
      name: "Coefficient (P)"
      description: "Avec coeff=1.0, un écart de -1°C => 100% chauffe."
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          mode: slider

    deadband:
      name: "Zone morte (°C)"
      description: "Autour de la consigne, pas de chauffe. Ex: 0.2 => ±0.2°C."
      default: 0.2
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

    securite_duty:
      name: "Sécurité capteur indisponible (%)"
      description: "Pourcentage de chauffe si le capteur est indisponible."
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 5
          mode: slider

mode: restart

trigger:
  - platform: time_pattern
    seconds: "/30"
    id: tick_30s

  - platform: time_pattern
    minutes: "/5"
    id: tick_5m

  - platform: state
    entity_id_
