blueprint:
  name: "Radiateur fil pilote - Régulation PWM (cycle 30s ou 5 min) + zone morte + sécurité"
  description: >
    Régulation temporelle (PWM).
    - Relais OFF = chauffe (Confort)
    - Relais ON  = hors-gel / arrêt
    - Zone morte (deadband)
    - Capteur indisponible => chauffe X% (défaut 50%)
    - Mode Hors Gel prioritaire
    - Cycle configurable: 30s (test) ou 5 min (prod)
  domain: automation

  input:
    fil_pilote_switch:
      name: "Relais / prise fil pilote"
      description: "Switch commandant le fil pilote (OFF=chauffe, ON=hors-gel)."
      selector:
        entity:
          domain: switch

    thermometre:
      name: "Capteur de température"
      selector:
        entity:
          domain: sensor

    mode_chauffage:
      name: "Mode chauffage (input_select)"
      description: "Doit contenir les valeurs 'Confort' et 'Hors Gel'."
      selector:
        entity:
          domain: input_select

    consigne:
      name: "Consigne (input_number)"
      selector:
        entity:
          domain: input_number

    cycle:
      name: "Cycle PWM"
      description: "Choisir 30s (test) ou 5 min (prod)."
      default: "5 min"
      selector:
        select:
          options:
            - "30 s"
            - "5 min"

    coeff:
      name: "Coefficient (P)"
      description: "Avec coeff=1.0, un écart de -1°C => 100% chauffe."
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          mode: slider

    deadband:
      name: "Zone morte (°C)"
      description: "Autour de la consigne, pas de chauffe. Ex: 0.2 => ±0.2°C."
      default: 0.2
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

    securite_duty:
      name: "Sécurité capteur indisponible (%)"
      description: "Pourcentage de chauffe si le capteur est indisponible."
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 5
          mode: slider

mode: restart

trigger:
  - platform: time_pattern
    seconds: "/30"
    id: tick_30s

  - platform: time_pattern
    minutes: "/5"
    id: tick_5m

  - platform: state
    entity_id: !input consigne
    id: param_change

  - platform: state
    entity_id: !input mode_chauffage
    id: param_change

variables:
  fil_pilote: !input fil_pilote_switch
  thermo: !input thermometre
  mode_ent: !input mode_chauffage
  consigne_ent: !input consigne

  cycle_choice: !input cycle
  cycle_s: >-
    {% if cycle_choice == '30 s' %}
      30
    {% else %}
      300
    {% endif %}

  coeff: !input coeff
  deadband: !input deadband
  securite_duty: !input securite_duty

  consigne: "{{ states(consigne_ent) | float(0) }}"
  temperature_str: "{{ states(thermo) }}"
  temperature: "{{ temperature_str | float(0) }}"

  erreur: "{{ temperature - consigne }}"
  abs_erreur: "{{ erreur | abs }}"

  duty_raw: "{{ (-erreur) * (coeff | float(1)) }}"

  duty: >-
    {% if temperature_str in ['unknown','unavailable','none',''] %}
      none
    {% elif abs_erreur <= (deadband | float(0)) %}
      0
    {% else %}
      {{ [ [ duty_raw, 0 ] | max, 1 ] | min }}
    {% endif %}

  securite_frac: "{{ (securite_duty | float(50)) / 100 }}"
  chauffe_s: >-
    {% if duty is none %}
      {{ (cycle_s * securite_frac) | round(0) | int }}
    {% else %}
      {{ (cycle_s * (duty | float(0))) | round(0) | int }}
    {% endif %}

  repos_s: "{{ cycle_s - chauffe_s }}"

action:
  # Filtre de tick selon le cycle choisi
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'tick_30s' and cycle_choice != '30 s' }}"
        sequence:
          - stop: "Cycle sur 5 min : tick 30s ignoré."
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'tick_5m' and cycle_choice != '5 min' }}"
        sequence:
          - stop: "Cycle sur 30s : tick 5 min ignoré."

  # Mode Hors Gel prioritaire
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(mode_ent, 'Hors Gel') }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ fil_pilote }}"
          - stop: "Mode Hors Gel actif."

  # PWM
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ chauffe_s <= 0 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ fil_pilote }}"

      - conditions:
          - condition: template
            value_template: "{{ chauffe_s >= cycle_s }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ fil_pilote }}"

    default:
      - service: switch.turn_off
        target:
          entity_id: "{{ fil_pilote }}"
      - delay:
          seconds: "{{ chauffe_s }}"
      - service: switch.turn_on
        target:
          entity_id: "{{ fil_pilote }}"
      - delay:
          seconds: "{{ repos_s }}"
